import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-100">
      <script type="javascript" src="https://merchi.co/static/js/dist/merchi.js">
</script>
      <body className={`d-flex flex-column h-100 ${inter.style}`}>{children}</body>
    </html>
  )
}
